name: CI - Build and Test

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/packages.lock.json

      - name: Restore
        run: dotnet restore HAGI.Robust.sln --locked-mode

      - name: Build (Release, warnings as errors)
        run: dotnet build HAGI.Robust.sln --no-restore -c Release -warnaserror

      - name: Test
        run: dotnet test HAGI.Robust.sln --no-build -c Release --logger "trx;LogFileName=test.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"
