name: Publish NuGet Package

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      VERSION: 0.1.0   

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Pack
        run: dotnet pack ./src/Hagi.Robust/Hagi.Robust.csproj \
          -c Release \
          -p:PackageVersion=${{ env.VERSION }} \
          -o ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.GITHUB_TOKEN }}